name = "QuantumGrav"
uuid = "f7c7699e-e939-438e-b944-97232f27dad4"
authors = ["""Harald  Mack <harald.mack@protonmail.com\n>"""]
version = "0.1.0"

[deps]
CausalSets = "2cd3ca5d-4cd6-4e37-88b9-1a897f702e70"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"

[sources]
CausalSets = {url = "https://codeberg.org/cyclopentane/CausalSets.jl"}

[compat]
CausalSets = "1.0.1"
Dates = "1.11.0"
Distributions = "0.25.120"
Graphs = "1.13.0"
HDF5 = "0.17.2"
JSONSchema = "1.5.0"
LinearAlgebra = "1.11.0"
Pkg = "1.11.0"
ProgressMeter = "1.10.4"
Random = "1.11.0"
SparseArrays = "1.11.0"
YAML = "0.4.14"
Zarr = "0.9.4"
